kind: Deployment
apiVersion: apps/v1
metadata:
  name: blast-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-blast-app
  template:
    metadata:
      labels:
        app: quarkus-blast-app
    spec:
      containers:
        - name: blast-postgres
          image: quay.io/redhat-user-workloads/rh-quarkus-tenant/quarkus-blast/blast-postgres:build-ac662-1688986144
          env:
            - name: PGDATA
              value: /work/data
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: user
          ports:
            - containerPort: 5432
              name: db-port
          resources:
            requests:
              cpu: "400m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          volumeMounts:
            - name: blast-postgres-data
              mountPath: /work
      volumes:
        - name: blast-postgres-data
          persistentVolumeClaim:
            claimName: blast-postgres-data
---
kind: Service
apiVersion: v1
metadata:
  name: blast-postgres
spec:
  selector:
    app: quarkus-blast-app
  ports:
    - protocol: TCP
      name: postgres-port
      port: 5432
      targetPort: 5432
selector:
  app: quarkus-blast-app
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blast-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
selector:
  app: quarkus-blast-app