kind: Deployment
apiVersion: apps/v1
metadata:
  name: blast-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-blast-app
  template:
    metadata:
      labels:
        app: quarkus-blast-app
    spec:
      containers:
        - name: blast-postgres
          image: blast-postgres:latest
          env:
            - name: PGDATA
              value: /work/data
            - name: POSTGRES_PASSWORD
              value: blast
            - name: POSTGRES_USER
              value: blast
          ports:
            - containerPort: 5432
              name: db-port
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: blast-postgres-data
              mountPath: /work
      volumes:
        - name: blast-postgres-data
          persistentVolumeClaim:
            claimName: blast-postgres-data
---
kind: Service
apiVersion: v1
metadata:
  name: blast-postgres
spec:
  type: NodePort
  selector:
    app: quarkus-blast
    component: blast-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
selector:
  app: quarkus-blast-app
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blast-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
selector:
  app: quarkus-blast-app