kind: Deployment
apiVersion: apps/v1
metadata:
  name: blast-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-blast-app
  template:
    metadata:
      labels:
        app: quarkus-blast-app
    spec:
      containers:
        - name: blast-quarkus
          image: quarkus-blast:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: QUARKUS_PROFILE
              value: prod,github,google,acme
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: user
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: google-client-id
                  optional: true
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: google-secret
                  optional: true
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: github-client-id
                  optional: true
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: github-secret
                  optional: true
            - name: BLAST_ADMINS
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: admins
                  optional: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: blast-quarkus
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: quarkus-blast-app