kind: Deployment
apiVersion: apps/v1
metadata:
  name: blast-quarkus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quarkus-blast-app
  template:
    metadata:
      labels:
        app: quarkus-blast-app
    spec:
      containers:
        - name: blast-quarkus
          image: quay.io/redhat-user-workloads/rh-quarkus-tenant/quarkus-blast/blast-quarkus:build-cf99e-1688736541
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: user
            - name: GOOGLE_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: google-provider
                  optional: true
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: google-client-id
                  optional: true
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: google-secret
                  optional: true
            - name: GITHUB_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: github-provider
                  optional: true
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: github-client-id
                  optional: true
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: github-secret
                  optional: true
            - name: BLAST_ADMINS
              valueFrom:
                secretKeyRef:
                  name: oidc-secrets
                  key: admins
                  optional: true
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: blast-quarkus
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: quarkus-blast-app